name: Cardia for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout
      
    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
      name: Install xmake

    - name: Build debug
      run: |
        xmake f -m debug -y
        xmake

    - name: Build release
      run: | 
        xmake f -m release -y
        xmake
    
    - name: Prepare artifacts
      run: |
        mkdir debug-artifact
        move build/debug-windows-x64/SandBox/bin/SandBox.exe debug-artifact/
        move build/debug-windows-x64/SandBox/bin/SandBox.pdb debug-artifact/
        
        mkdir release-artifact
        move build/release-windows-x64/SandBox/bin/SandBox.exe release-artifact/

    - uses: actions/upload-artifact@v2
      with:
        name: Cardia-windows-debug-${{ github.run_id }}
        path: debug-artifact/
      name: Upload debug artifact
      
    - uses: actions/upload-artifact@v2
      with:
        name: Cardia-windows-release-${{ github.run_id }}
        path: release-artifact/
      name: Upload release artifact
